name: Ping Twitter Bot
on: [push]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send signal to GitBot Brain
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/penne-not-pasta/GitBot/dispatches \
          -d '{"event_type": "tweet_trigger", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
